// swift-tools-version: 6.0

import PackageDescription

let package = Package(
    name: "{{PROJECT_NAME}}",
    platforms: [
        .iOS(.v13)
    ],
    products: [
        .library(
            name: "{{PROJECT_NAME}}",
            targets: ["{{PROJECT_NAME}}"]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/dev-hann/gyo.git", from: "0.1.0"),
        // BEGIN GYO PLUGINS - DO NOT EDIT
        // This section is automatically generated by `gyo install`
        // END GYO PLUGINS
    ],
    targets: [
        .target(
            name: "{{PROJECT_NAME}}",
            dependencies: [
                .product(name: "GyoBridge", package: "gyo"),
                // BEGIN GYO PLUGINS - DO NOT EDIT
                // This section is automatically generated by `gyo install`
                // END GYO PLUGINS
            ],
            path: "Sources",
            resources: [
                .process("Resources")
            ]
        )
    ]
)
