// swift-tools-version: 6.0

import PackageDescription

let package = Package(
    name: "{{PROJECT_NAME}}",
    platforms: [
        .iOS(.v13)
    ],
    products: [
        .library(
            name: "{{PROJECT_NAME}}",
            targets: ["{{PROJECT_NAME}}"]
        )
    ],
    dependencies: [
        // BEGIN GYO PLUGINS - DO NOT EDIT
        // This section is automatically generated by `gyo install`
        // END GYO PLUGINS
    ],
    targets: [
        .target(
            name: "{{PROJECT_NAME}}",
            dependencies: [
                // BEGIN GYO PLUGINS - DO NOT EDIT
                // This section is automatically generated by `gyo install`
                // END GYO PLUGINS
            ],
            path: "Sources",
            resources: [
                .process("Resources")
            ]
        )
    ]
)
