import * as path from 'path';
import { logger } from './logger.js';
import { pathExists, readFile, writeFile } from './fs.js';
import { PluginMetadata, PluginManager } from './plugin-manager.js';

export class AndroidPluginIntegrator {
  private projectRoot: string;
  private pluginManager: PluginManager;

  constructor(projectRoot: string = process.cwd()) {
    this.projectRoot = projectRoot;
    this.pluginManager = new PluginManager(projectRoot);
  }

  /**
   * Update android/settings.gradle with plugin includes
   */
  async updateSettingsGradle(plugins: PluginMetadata[]): Promise<void> {
    const settingsGradlePath = path.join(this.projectRoot, 'android', 'settings.gradle');

    if (!(await pathExists(settingsGradlePath))) {
      logger.warn('android/settings.gradle not found, skipping Android plugin integration');
      return;
    }

    let content = await readFile(settingsGradlePath);

    // Generate plugin includes
    let pluginIncludes = '';
    for (const plugin of plugins) {
      if (!plugin.platforms.android) {
        continue;
      }

      const moduleName = plugin.platforms.android.moduleName;
      const relativePath = this.pluginManager.getRelativePluginPath(plugin, 'android');

      pluginIncludes += `include ':${moduleName}'\n`;
      pluginIncludes += `project(':${moduleName}').projectDir = new File(rootProject.projectDir, '${relativePath}')\n\n`;
    }

    // Replace the auto-generated section
    const beginMarker = '// BEGIN GYO PLUGINS - DO NOT EDIT';
    const endMarker = '// END GYO PLUGINS';

    content = this.replaceGeneratedSection(
      content,
      beginMarker,
      endMarker,
      pluginIncludes.trimEnd()
    );

    await writeFile(settingsGradlePath, content);
    logger.verbose('Updated android/settings.gradle');
  }

  /**
   * Update android/app/build.gradle with plugin dependencies
   */
  async updateAppBuildGradle(plugins: PluginMetadata[]): Promise<void> {
    const buildGradlePath = path.join(this.projectRoot, 'android', 'app', 'build.gradle');

    if (!(await pathExists(buildGradlePath))) {
      logger.warn('android/app/build.gradle not found, skipping Android plugin integration');
      return;
    }

    let content = await readFile(buildGradlePath);

    // Generate plugin dependencies
    let pluginDependencies = '';
    for (const plugin of plugins) {
      if (!plugin.platforms.android) {
        continue;
      }

      const moduleName = plugin.platforms.android.moduleName;
      pluginDependencies += `    implementation project(':${moduleName}')\n`;
    }

    // Replace the auto-generated section
    const beginMarker = '// BEGIN GYO PLUGINS - DO NOT EDIT';
    const endMarker = '// END GYO PLUGINS';

    content = this.replaceGeneratedSection(
      content,
      beginMarker,
      endMarker,
      pluginDependencies.trimEnd()
    );

    await writeFile(buildGradlePath, content);
    logger.verbose('Updated android/app/build.gradle');
  }

  /**
   * Helper: Find and replace auto-generated section
   */
  private replaceGeneratedSection(
    content: string,
    beginMarker: string,
    endMarker: string,
    newContent: string
  ): string {
    const beginIndex = content.indexOf(beginMarker);
    const endIndex = content.indexOf(endMarker);

    if (beginIndex === -1 || endIndex === -1) {
      logger.warn(`Plugin markers not found. Please ensure your gradle files have the required markers:\n${beginMarker}\n${endMarker}`);
      return content;
    }

    // Find the end of the begin marker line
    const beginLineEnd = content.indexOf('\n', beginIndex);
    
    // Construct the new section
    const before = content.substring(0, beginLineEnd + 1);
    const after = content.substring(endIndex);

    // Add comment and new content
    const generatedComment = '// This section is automatically generated by `gyo install`\n';
    const middleContent = newContent ? generatedComment + newContent + '\n' : generatedComment;

    return before + middleContent + after;
  }
}
