import * as path from 'path';
import { logger } from './logger.js';
import { pathExists, readFile, writeFile } from './fs.js';
import { PluginMetadata, PluginManager } from './plugin-manager.js';

export class IosPluginIntegrator {
  private projectRoot: string;
  private pluginManager: PluginManager;

  constructor(projectRoot: string = process.cwd()) {
    this.projectRoot = projectRoot;
    this.pluginManager = new PluginManager(projectRoot);
  }

  /**
   * Update ios/Package.swift with plugin dependencies
   */
  async updatePackageSwift(plugins: PluginMetadata[]): Promise<void> {
    const packageSwiftPath = path.join(this.projectRoot, 'ios', 'Package.swift');

    if (!(await pathExists(packageSwiftPath))) {
      logger.warn('ios/Package.swift not found, skipping iOS plugin integration');
      return;
    }

    let content = await readFile(packageSwiftPath);

    // Generate dependencies section
    const dependencies = this.generateDependencies(plugins);
    
    // Generate target dependencies section
    const targetDependencies = this.generateTargetDependencies(plugins);

    // Replace the auto-generated sections
    const beginMarker = '// BEGIN GYO PLUGINS - DO NOT EDIT';
    const endMarker = '// END GYO PLUGINS';

    // First, replace dependencies section
    content = this.replaceGeneratedSection(
      content,
      beginMarker,
      endMarker,
      dependencies,
      0 // First occurrence
    );

    // Then, replace target dependencies section
    content = this.replaceGeneratedSection(
      content,
      beginMarker,
      endMarker,
      targetDependencies,
      1 // Second occurrence
    );

    await writeFile(packageSwiftPath, content);
    logger.verbose('Updated ios/Package.swift');
  }

  /**
   * Generate dependencies array entries
   */
  private generateDependencies(plugins: PluginMetadata[]): string {
    const lines: string[] = [];

    for (const plugin of plugins) {
      if (!plugin.platforms.ios) {
        continue;
      }

      const relativePath = this.pluginManager.getRelativePluginPath(plugin, 'ios');
      
      // Get the package name from the path (last directory name)
      const packageName = plugin.platforms.ios.sourceDir || 'ios';
      
      lines.push(`        .package(path: "${relativePath}"),`);
    }

    return lines.join('\n');
  }

  /**
   * Generate target dependencies array entries
   */
  private generateTargetDependencies(plugins: PluginMetadata[]): string {
    const lines: string[] = [];

    for (const plugin of plugins) {
      if (!plugin.platforms.ios) {
        continue;
      }

      const productName = plugin.platforms.ios.packageName;
      
      // Extract package name (e.g., "@gyo-framework/camera" -> "camera")
      let packageIdentifier = plugin.name;
      if (packageIdentifier.includes('/')) {
        packageIdentifier = packageIdentifier.split('/').pop()!;
      }
      
      lines.push(`                .product(name: "${productName}", package: "${packageIdentifier}"),`);
    }

    return lines.join('\n');
  }

  /**
   * Helper: Find and replace auto-generated section
   * @param occurrence Which occurrence to replace (0-indexed)
   */
  private replaceGeneratedSection(
    content: string,
    beginMarker: string,
    endMarker: string,
    newContent: string,
    occurrence: number = 0
  ): string {
    let currentOccurrence = 0;
    let searchStart = 0;

    while (currentOccurrence <= occurrence) {
      const beginIndex = content.indexOf(beginMarker, searchStart);
      
      if (beginIndex === -1) {
        if (currentOccurrence === 0) {
          logger.warn(`Plugin markers not found in Package.swift. Please ensure the file has the required markers:\n${beginMarker}\n${endMarker}`);
        }
        return content;
      }

      const endIndex = content.indexOf(endMarker, beginIndex);
      
      if (endIndex === -1) {
        logger.warn(`End marker not found in Package.swift after begin marker at position ${beginIndex}`);
        return content;
      }

      if (currentOccurrence === occurrence) {
        // This is the occurrence we want to replace
        const beginLineEnd = content.indexOf('\n', beginIndex);
        const before = content.substring(0, beginLineEnd + 1);
        const after = content.substring(endIndex);

        const generatedComment = '        // This section is automatically generated by `gyo install`\n';
        const middleContent = newContent ? generatedComment + newContent + '\n' : generatedComment;

        return before + middleContent + after;
      }

      // Move past this occurrence
      searchStart = endIndex + endMarker.length;
      currentOccurrence++;
    }

    return content;
  }
}
